version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trng-1558"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zgn983usru2w"
s3_prefix = "trng-1558"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
