AWSTemplateFormatVersion: 2010-09-09

Description: >-
  230109 Serverless Project-3

Transform:
- AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test-function/
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        Test:
          Type: Api
          Properties:
            Path: /test
            Method: get
  ApproveDenyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: approve-deny-function/
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        Test:
          Type: Api
          Properties:
            Path: /reimbursements/:id/status
            Method: patch
  AddReimbursements:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add-reimbursements-function/
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 60
      Events:
        AddReimbursements:
          Type: Api
          Properties:
            Path: /reimbursements
            Method: post
      Environment:
        Variables:
          REIMBURSEMENTS_TABLE_NAME: !Ref ReimbursementsTable
          RECEIPTS_BUCKET_NAME: !Ref ReceiptsBucket
          JWT_SIGNING_SECRET: psstthisisthesecret
      Policies:
        - Statement:
            Effect: Allow
            Action:
             - dynamodb:PutItem
            Resource: !GetAtt ReimbursementsTable.Arn
        - S3WritePolicy:
            BucketName: !Ref ReceiptsBucket
  ReimbursementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ReceiptsBucket:
    Type: AWS::S3::Bucket

Outputs:
  Endpoint:
    Description: "Endpoint for API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
