AWSTemplateFormatVersion: 2010-09-09

Description: >-
  230109 Serverless Project-3

Transform:
- AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test-function/
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        Test:
          Type: Api
          Properties:
            Path: /test
            Method: get
  ApproveDenyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: approve-deny-function/
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        Test:
          Type: Api
          Properties:
            Path: /reimbursements/:id/status
            Method: patch
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: register-function/
      Handler: register-handler.handler
      Runtime: nodejs16.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: UsersTable
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
      Events:
        Test:
          Type: Api
          Properties:
            Path: /users
            Method: post

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  Endpoint:
    Description: "Endpoint for API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
